namespace APIBlox.AspNetCore.Contracts
{
    /// <summary>
    ///     Marker Interface
    /// </summary>
    /// <autogeneratedoc />
    public interface IDynamicControllerConfiguration
    {
    }
}
