using System.Collections.ObjectModel;
using APIBlox.AspNetCore.Types;

namespace APIBlox.AspNetCore.Types
{
    /// <summary>
    ///     Metadata class for <see cref="RequestErrorObject"/>
    /// </summary>
    public class RequestErrorResult //: RequestErrorObject
    {
        private RequestErrorResult()
        {

        }

        /// <summary>
        ///     [REQUIRED]
        ///     <para>
        ///         Required when <see cref="Errors" /> is not empty.
        ///     </para>
        /// </summary>
        public string Detail { get; }

        /// <summary>
        ///     Gets or sets the inner errors.
        /// </summary>
        /// <remarks>
        ///     An object containing more specific information.
        /// </remarks>
        /// <value>The inner error.</value>
        public Collection<RequestError> Errors { get; } = new Collection<RequestError>();

        /// <summary>
        ///     [REQUIRED]
        ///     <para>
        ///         A URI reference that identifies the specific occurrence of the problem.It may or may not yield further
        ///         information.
        ///     </para>
        /// </summary>
        public string Instance { get; }


        /// <summary>
        ///     [REQUIRED]
        ///     <para>
        ///         The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        ///     </para>
        /// </summary>
        public int? Status { get; }

        /// <summary>
        ///     [REQUIRED]
        ///     <para>
        ///         A short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
        ///         of the problem, except for purposes of localization(e.g., using proactive content negotiation;
        ///         see[RFC7231], Section 3.4).
        ///     </para>
        /// </summary>
        public string Title { get; }

        /// <summary>
        ///     [REQUIRED] defaults to "about:blank"
        ///     <para>
        ///         A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
        ///         de-referenced, it provide human-readable documentation for the problem type
        ///         (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be
        ///         "about:blank".
        ///     </para>
        /// </summary>
        public string Type { get; }
    }
}
